# Generated by Django 4.1.7 on 2023-04-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after_hours', models.FloatField()),
                ('close', models.FloatField()),
                ('from_field', models.CharField(max_length=50)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('open', models.FloatField()),
                ('pre_market', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('volume', models.IntegerField()),
                ('performance', models.JSONField()),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
