# Generated by Django 4.2 on 2023-04-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='after_hours',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='close',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='from_field',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='high',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='low',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='open',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='performance',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='pre_market',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='volume',
            field=models.IntegerField(null=True),
        ),
    ]
